name: Upload to Notion

on:
  schedule:
    - cron: '33 15 * * *'  # UTC 15:56 - KST 12:33 자동 실행
  workflow_dispatch:  # 수동 실행 허용

jobs:
  upload-to-notion:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Python 설정
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. 의존성 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install notion-client pytz

      # 4. Notion에 업로드 실행
      - name: Upload papers to Notion
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
        run: |
          python upload_to_notion.py

      # 5. 로그 출력
      - name: Print completion message
        run: echo "✅ Papers have been successfully uploaded to Notion!"
